import { type NextPage } from "next";
import Head from "next/head";
import { Button, MantineProvider, TextInput } from "@mantine/core";
import { useState } from "react";
import VariablesComponent from "~/components/VariablesComponent";

const Home: NextPage = () => {
  const [text, setText] = useState("");
  const [prevText, setPrevText] = useState("");
  const [showChat, setShowChat] = useState(false);

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setPrevText(text);
    setShowChat(true);
  }

  function handleTextChange(event: React.ChangeEvent<HTMLInputElement>) {
    setText(event.target.value);
  }

  return (
    <>
      <MantineProvider theme={{ colorScheme: "dark" }}>
        <Head>
          <title>Shiny Garbanzo</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              <span className="text-[hsl(280,100%,70%)]">Shiny</span> Garbanzo
            </h1>
          </div>
          <form
            onSubmit={handleSubmit}
            className="flex flex-col items-center justify-center"
          >
            <TextInput
              withAsterisk
              id="text"
              label="What do you want to do?"
              radius="sm"
              placeholder="Enter text here"
              onChange={handleTextChange}
            />
            <Button
              variant="gradient"
              color="blue"
              style={{ marginTop: 8 }}
              type="submit"
            >
              Submit
            </Button>
          </form>
          {showChat && text === prevText && <VariablesComponent text={text} />}
        </main>
      </MantineProvider>
    </>
  );
};

export default Home;
